---
mas_installed_apps:
  - { id: 1013592989, name: "App Icon Resizer" }
  - { id: 497799835, name: "Xcode" }
  - { id: 441258766, name: "Magnet" }
  - { id: 1483334848, name: "Pieta" }
  - { id: 1147396723, name: "WhatsApp" }
  - { id: 409201541, name: "Pages" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1193539993, name: "Brother iPrint&Scan" }
configure_dock: false

homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages:
  - ansible-lint # Checks ansible playbooks for practices and behaviour
  - cheat # Create and view interactive cheat sheets for *nix commands
  - coreutils # GNU File, Shell, and Text utilities
  - ctags # Reimplementation of ctags(1)
  - ffmpeg # Play, record, convert, and stream audio and video
  - node # node.js and npm
  - odt2txt # Convert OpenDocument files to plain text
  - shellcheck # Static analysis and lint tool, for (ba)sh scripts
  - stow # Organize software neatly under a single directory tree (e.g. /usr/local)
  - zsh-completions # Additional completion definitions for zsh
  - zsh-fast-syntax-highlighting # Feature-rich syntax highlighting for Zsh

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: false

homebrew_taps:
    - homebrew/core
    - idleberg/dbxcli
    - koekeishiya/formulae/yabai
    - koekeishiya/formulae/skhd

homebrew_cask_apps:
  - dropbox
  - logseq
  - background-music
  - balsamiq-wireframes
  - monero-wallet
  - calibre
  - mpv
  - docker
  - obs
  - electrum
  - rectangle
  - hazeover
  - spotify
  - keepassxc
  - kobo
  - libreoffice

homebrew_cask_uninstalled_apps: []

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'

homebrew_clear_cache: false

homebrew_folders_additional: []
