#!/usr/bin/env zsh
set -x

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="nvim,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/Dropbox/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  stow --delete $folder
  stow --target=~ $folder
done
popd
